package battletech.tactical.model

public object MechModels {
    private val registry: Map<String, MechModel> = listOf(
        MechModel(
            variant = "LCT-1V",
            name = "Locust LCT-1V",
            tonnage = 20,
            walkingMP = 8,
            runningMP = 12,
            armor = ArmorLayout(
                head = 8,
                centerTorso = 10, centerTorsoRear = 2,
                leftTorso = 8, leftTorsoRear = 2,
                rightTorso = 8, rightTorsoRear = 2,
                leftArm = 4, rightArm = 4,
                leftLeg = 4, rightLeg = 4,
            ),
            weapons = listOf(Weapons::mediumLaser, Weapons::machineGun, Weapons::machineGun),
        ),
        MechModel(
            variant = "STG-3R",
            name = "Stinger STG-3R",
            tonnage = 20,
            walkingMP = 6,
            runningMP = 9,
            jumpMP = 6,
            armor = ArmorLayout(
                head = 6,
                centerTorso = 6, centerTorsoRear = 2,
                leftTorso = 6, leftTorsoRear = 2,
                rightTorso = 6, rightTorsoRear = 2,
                leftArm = 4, rightArm = 4,
                leftLeg = 5, rightLeg = 5,
            ),
            weapons = listOf(Weapons::mediumLaser, Weapons::machineGun, Weapons::machineGun),
        ),
        MechModel(
            variant = "WSP-1A",
            name = "Wasp WSP-1A",
            tonnage = 20,
            walkingMP = 6,
            runningMP = 9,
            jumpMP = 6,
            armor = ArmorLayout(
                head = 4,
                centerTorso = 6, centerTorsoRear = 2,
                leftTorso = 4, leftTorsoRear = 2,
                rightTorso = 4, rightTorsoRear = 2,
                leftArm = 4, rightArm = 4,
                leftLeg = 5, rightLeg = 5,
            ),
            weapons = listOf(Weapons::mediumLaser, Weapons::srm2),
        ),
        MechModel(
            variant = "PXH-1",
            name = "Phoenix Hawk PXH-1",
            tonnage = 45,
            walkingMP = 6,
            runningMP = 9,
            jumpMP = 6,
            heatSinkCapacity = 13,
            armor = ArmorLayout(
                head = 6,
                centerTorso = 23, centerTorsoRear = 5,
                leftTorso = 18, leftTorsoRear = 4,
                rightTorso = 18, rightTorsoRear = 4,
                leftArm = 10, rightArm = 10,
                leftLeg = 15, rightLeg = 15,
            ),
            weapons = listOf(Weapons::largeLaser, Weapons::mediumLaser, Weapons::mediumLaser, Weapons::machineGun, Weapons::machineGun),
        ),
        MechModel(
            variant = "GRF-1N",
            name = "Griffin GRF-1N",
            tonnage = 55,
            walkingMP = 5,
            runningMP = 8,
            jumpMP = 5,
            heatSinkCapacity = 12,
            armor = ArmorLayout(
                head = 9,
                centerTorso = 20, centerTorsoRear = 7,
                leftTorso = 20, leftTorsoRear = 6,
                rightTorso = 20, rightTorsoRear = 6,
                leftArm = 14, rightArm = 14,
                leftLeg = 18, rightLeg = 18,
            ),
            weapons = listOf(Weapons::ppc, Weapons::lrm10),
        ),
        MechModel(
            variant = "SHD-2H",
            name = "Shadow Hawk SHD-2H",
            tonnage = 55,
            walkingMP = 5,
            runningMP = 8,
            jumpMP = 5,
            heatSinkCapacity = 12,
            armor = ArmorLayout(
                head = 9,
                centerTorso = 23, centerTorsoRear = 8,
                leftTorso = 18, leftTorsoRear = 6,
                rightTorso = 18, rightTorsoRear = 6,
                leftArm = 16, rightArm = 16,
                leftLeg = 26, rightLeg = 26,
            ),
            weapons = listOf(Weapons::ac5, Weapons::lrm5, Weapons::srm2, Weapons::mediumLaser),
        ),
        MechModel(
            variant = "WHM-6R",
            name = "Warhammer WHM-6R",
            tonnage = 70,
            walkingMP = 4,
            runningMP = 6,
            heatSinkCapacity = 18,
            armor = ArmorLayout(
                head = 9,
                centerTorso = 20, centerTorsoRear = 8,
                leftTorso = 14, leftTorsoRear = 9,
                rightTorso = 14, rightTorsoRear = 9,
                leftArm = 20, rightArm = 20,
                leftLeg = 15, rightLeg = 15,
            ),
            weapons = listOf(
                Weapons::ppc, Weapons::ppc,
                Weapons::mediumLaser, Weapons::mediumLaser,
                Weapons::smallLaser, Weapons::smallLaser,
                Weapons::machineGun, Weapons::machineGun,
                Weapons::srm6,
            ),
        ),
        MechModel(
            variant = "MAD-3R",
            name = "Marauder MAD-3R",
            tonnage = 75,
            walkingMP = 4,
            runningMP = 6,
            heatSinkCapacity = 18,
            armor = ArmorLayout(
                head = 9,
                centerTorso = 35, centerTorsoRear = 10,
                leftTorso = 17, leftTorsoRear = 8,
                rightTorso = 17, rightTorsoRear = 8,
                leftArm = 22, rightArm = 22,
                leftLeg = 18, rightLeg = 18,
            ),
            weapons = listOf(
                Weapons::ppc, Weapons::ppc,
                Weapons::mediumLaser, Weapons::mediumLaser,
                Weapons::ac5,
            ),
        ),
        MechModel(
            variant = "ARC-2R",
            name = "Archer ARC-2R",
            tonnage = 70,
            walkingMP = 4,
            runningMP = 6,
            heatSinkCapacity = 15,
            armor = ArmorLayout(
                head = 9,
                centerTorso = 33, centerTorsoRear = 10,
                leftTorso = 24, leftTorsoRear = 6,
                rightTorso = 24, rightTorsoRear = 6,
                leftArm = 22, rightArm = 22,
                leftLeg = 26, rightLeg = 26,
            ),
            weapons = listOf(
                Weapons::lrm20, Weapons::lrm20,
                Weapons::mediumLaser, Weapons::mediumLaser, Weapons::mediumLaser, Weapons::mediumLaser,
            ),
        ),
        MechModel(
            variant = "AS7-D",
            name = "Atlas AS7-D",
            tonnage = 100,
            walkingMP = 3,
            runningMP = 5,
            heatSinkCapacity = 20,
            armor = ArmorLayout(
                head = 9,
                centerTorso = 47, centerTorsoRear = 14,
                leftTorso = 32, leftTorsoRear = 10,
                rightTorso = 32, rightTorsoRear = 10,
                leftArm = 34, rightArm = 34,
                leftLeg = 41, rightLeg = 41,
            ),
            weapons = listOf(
                Weapons::ac20,
                Weapons::lrm20,
                Weapons::srm6,
                Weapons::mediumLaser, Weapons::mediumLaser, Weapons::mediumLaser, Weapons::mediumLaser,
            ),
        ),
        MechModel(
            variant = "HBK-4G",
            name = "Hunchback HBK-4G",
            tonnage = 50,
            walkingMP = 4,
            runningMP = 6,
            armor = ArmorLayout(
                head = 9,
                centerTorso = 24, centerTorsoRear = 8,
                leftTorso = 20, leftTorsoRear = 4,
                rightTorso = 20, rightTorsoRear = 4,
                leftArm = 10, rightArm = 10,
                leftLeg = 16, rightLeg = 16,
            ),
            weapons = listOf(Weapons::ac20),
        ),
        MechModel(
            variant = "WVR-6R",
            name = "Wolverine WVR-6R",
            tonnage = 55,
            walkingMP = 5,
            runningMP = 8,
            jumpMP = 5,
            armor = ArmorLayout(
                head = 9,
                centerTorso = 22, centerTorsoRear = 8,
                leftTorso = 16, leftTorsoRear = 5,
                rightTorso = 16, rightTorsoRear = 5,
                leftArm = 14, rightArm = 14,
                leftLeg = 18, rightLeg = 18,
            ),
            weapons = listOf(Weapons::srm6, Weapons::mediumLaser),
        ),
    ).associateBy { it.variant }

    public operator fun get(variant: String): MechModel =
        registry[variant] ?: error("Unknown mech variant: $variant")
}
