package battletech.tactical.heat

import battletech.tactical.model.MovementMode
import battletech.tactical.unit.HeatSource
import battletech.tactical.unit.Weapon

/**
 * Heat generated by a committed (or previewed) move. Stationary / turn-in-place
 * (0 hexes entered) generates none (an empty list); walking is a flat +1, running
 * a flat +2, jumping is one heat per hex jumped with a floor of 3. This is the
 * single source of truth used by both the movement commit handler and the TUI
 * gray preview, so the preview can never drift from what is actually applied.
 */
public fun movementHeatSources(mode: MovementMode, hexesMoved: Int): List<HeatSource> = when {
    hexesMoved <= 0 -> emptyList()
    mode == MovementMode.WALK -> listOf(HeatSource("Walking", 1))
    mode == MovementMode.RUN -> listOf(HeatSource("Running", 2))
    else -> listOf(HeatSource("Jumping", maxOf(3, hexesMoved)))
}

/** Heat generated by firing [weapon]. */
public fun weaponHeatSource(weapon: Weapon): HeatSource =
    HeatSource(weapon.name, weapon.heat)
