package tenter.icons

// Nerd Fonts icons (https://www.nerdfonts.com/cheat-sheet). Raw codepoints only — what each glyph
// *means* to a host application (a dice roll, a destroyed unit, a terrain type, …) is the host's
// own vocabulary, not this catalog's.
public val NF_MD_DICE_1: String = String(Character.toChars(0xF01CA))
public val NF_MD_DICE_2: String = String(Character.toChars(0xF01CB))
public val NF_MD_DICE_3: String = String(Character.toChars(0xF01CC))
public val NF_MD_DICE_4: String = String(Character.toChars(0xF01CD))
public val NF_MD_DICE_5: String = String(Character.toChars(0xF01CE))
public val NF_MD_DICE_6: String = String(Character.toChars(0xF01CF))
public val NF_MD_WALK: String = String(Character.toChars(0xF0583))
public val NF_MD_RUN_FAST: String = String(Character.toChars(0xF046E))
public val NF_MD_ROCKET_LAUNCH: String = String(Character.toChars(0xF14DE))
public val NF_MD_TARGET: String = String(Character.toChars(0xF04FE))
public val NF_MD_BULLSEYE_ARROW: String = String(Character.toChars(0xF08C9))
public val NF_MD_CROSSHAIRS_OFF: String = String(Character.toChars(0xF0F45))
public val NF_MD_DICE_MULTIPLE_OUTLINE: String = String(Character.toChars(0xF1156))
public val NF_MD_CHECKBOX_BLANK_CIRCLE_OUTLINE: String = String(Character.toChars(0xF0130))
public val NF_MD_AMMUNITION: String = String(Character.toChars(0xF0CE8))
public val NF_FA_INFINITY: String = String(Character.toChars(0xEDFE))
public val NF_MD_IMAGE_BROKEN: String = String(Character.toChars(0xF02ED))
public val NF_FA_CHAIN_BROKEN: String = String(Character.toChars(0xF127))
public val NF_FA_BOMB: String = String(Character.toChars(0xF1E2))
public val NF_MD_RADIOACTIVE_CIRCLE: String = String(Character.toChars(0xF185D))
public val NF_MD_SYNC_CIRCLE: String = String(Character.toChars(0xF1378))
public val NF_MD_EYE_CIRCLE: String = String(Character.toChars(0xF0B94))
public val NF_MD_ACCOUNT_CIRCLE: String = String(Character.toChars(0xF0009))
public val NF_MD_SKULL: String = String(Character.toChars(0xF068C))
public val NF_MD_ROBOT_DEAD: String = String(Character.toChars(0xF16A1))
public val NF_MD_LAN_CONNECT: String = String(Character.toChars(0xF0318))
public val NF_MD_TRANSFER_DOWN: String = String(Character.toChars(0xF0DA1))
public val NF_MD_TRANSFER_UP: String = String(Character.toChars(0xF0DA3))
public val NF_MD_ACCOUNT_ALERT: String = String(Character.toChars(0xF0005))
public val NF_MD_SLEEP: String = String(Character.toChars(0xF04B2))
public val NF_MD_SLEEP_OFF: String = String(Character.toChars(0xF04B3))
public val NF_MD_THERMOMETER_CHEVRON_DOWN: String = String(Character.toChars(0xF0E02))
public val NF_MD_THERMOMETER_CHEVRON_UP: String = String(Character.toChars(0xF0E03))
public val NF_MD_POWER: String = String(Character.toChars(0xF0425))
public val NF_MD_RESTART: String = String(Character.toChars(0xF0709))
public val NF_MD_TROPHY: String = String(Character.toChars(0xF0538))
public val NF_MD_PISTOL: String = String(Character.toChars(0xF0703))
public val NF_MD_BOXING_GLOVE: String = String(Character.toChars(0xF0B65))

// Terrain icons (nf-md-tree_outline, nf-md-tree and another Nerd Fonts icons are above U+FFFF, need surrogate pairs)
public val NF_MD_TREE_OUTLINE: String = String(Character.toChars(0xF0E69))
public val NF_MD_PINE_TREE: String = String(Character.toChars(0xF0531))
public val NF_MD_WAVES: String = String(Character.toChars(0xF078D))
public val NF_MD_GRAIN: String = String(Character.toChars(0xF0D7C))

// Numeric badge icons (nf-md-numeric_N_box_multiple)
public val NF_MD_NUMERIC_1_BOX_MULTIPLE: String = String(Character.toChars(0xF0F0F))
public val NF_MD_NUMERIC_2_BOX_MULTIPLE: String = String(Character.toChars(0xF0F10))
public val NF_MD_NUMERIC_3_BOX_MULTIPLE: String = String(Character.toChars(0xF0F11))
public val NF_MD_NUMERIC_4_BOX_MULTIPLE: String = String(Character.toChars(0xF0F12))
public val NF_MD_NUMERIC_5_BOX_MULTIPLE: String = String(Character.toChars(0xF0F13))
public val NF_MD_NUMERIC_6_BOX_MULTIPLE: String = String(Character.toChars(0xF0F14))
public val NF_MD_NUMERIC_7_BOX_MULTIPLE: String = String(Character.toChars(0xF0F15))
public val NF_MD_NUMERIC_8_BOX_MULTIPLE: String = String(Character.toChars(0xF0F16))
public val NF_MD_NUMERIC_9_BOX_MULTIPLE: String = String(Character.toChars(0xF0F17))

// Numeric badge outline icons (nf-md-numeric_N_box_multiple_outline)
public val NF_MD_NUMERIC_1_BOX_MULTIPLE_OUTLINE: String = String(Character.toChars(0xF03A5))
public val NF_MD_NUMERIC_2_BOX_MULTIPLE_OUTLINE: String = String(Character.toChars(0xF03A8))
public val NF_MD_NUMERIC_3_BOX_MULTIPLE_OUTLINE: String = String(Character.toChars(0xF03AB))
public val NF_MD_NUMERIC_4_BOX_MULTIPLE_OUTLINE: String = String(Character.toChars(0xF03B2))
public val NF_MD_NUMERIC_5_BOX_MULTIPLE_OUTLINE: String = String(Character.toChars(0xF03AF))
public val NF_MD_NUMERIC_6_BOX_MULTIPLE_OUTLINE: String = String(Character.toChars(0xF03B4))
public val NF_MD_NUMERIC_7_BOX_MULTIPLE_OUTLINE: String = String(Character.toChars(0xF03B7))
public val NF_MD_NUMERIC_8_BOX_MULTIPLE_OUTLINE: String = String(Character.toChars(0xF03BA))
public val NF_MD_NUMERIC_9_BOX_MULTIPLE_OUTLINE: String = String(Character.toChars(0xF03BD))

// Thin arrow icons
public val NF_MD_ARROW_UP_THIN_N: String = String(Character.toChars(0xF09C7))
public val NF_MD_ARROW_UP_THIN_NE: String = String(Character.toChars(0xF09C5))
public val NF_MD_ARROW_UP_THIN_SE: String = String(Character.toChars(0xF09B9))
public val NF_MD_ARROW_UP_THIN_S: String = String(Character.toChars(0xF09BF))
public val NF_MD_ARROW_UP_THIN_SW: String = String(Character.toChars(0xF09B7))
public val NF_MD_ARROW_UP_THIN_NW: String = String(Character.toChars(0xF09C3))

// Bold outline arrow icons (larger arrows)
public val NF_MD_ARROW_UP_BOLD_OUTLINE: String = String(Character.toChars(0xF09C7))
public val NF_MD_ARROW_TOP_RIGHT_BOLD_OUTLINE: String = String(Character.toChars(0xF09C5))
public val NF_MD_ARROW_BOTTOM_RIGHT_BOLD_OUTLINE: String = String(Character.toChars(0xF09B9))
public val NF_MD_ARROW_DOWN_BOLD_OUTLINE: String = String(Character.toChars(0xF09BF))
public val NF_MD_ARROW_BOTTOM_LEFT_BOLD_OUTLINE: String = String(Character.toChars(0xF09B7))
public val NF_MD_ARROW_TOP_LEFT_BOLD_OUTLINE: String = String(Character.toChars(0xF09C3))

// Plain arrow icons (smaller arrows)
public val NF_MD_ARROW_UP: String = String(Character.toChars(0xF005D))
public val NF_MD_ARROW_TOP_RIGHT: String = String(Character.toChars(0xF005C))
public val NF_MD_ARROW_BOTTOM_RIGHT: String = String(Character.toChars(0xF0043))
public val NF_MD_ARROW_DOWN: String = String(Character.toChars(0xF0045))
public val NF_MD_ARROW_BOTTOM_LEFT: String = String(Character.toChars(0xF0042))
public val NF_MD_ARROW_TOP_LEFT: String = String(Character.toChars(0xF005B))
